language: c
before_install:
- sudo apt-get update -qq
install:
- sudo apt-get install -qq gcc-avr binutils-avr avr-libc
script: make -C firmware
deploy:
  provider: releases
  api_key:
    secure: TtKe2n1Sxr+TwYipFnJYlwVjBySX7W2sf1K/Idtt14BP953IohCobLqk29wC/WvkHQH7QFRuoRTcX8zN97P4smAm0yz/7EjmXb5I8CUPWHzDV4WNEshykJgu/HWl8BtnL/E3TtzoN3j34ASOJNYeHmwNti40QqbQR7mrb7+b6dM3EsqAP+97envrC9eg4FITrAtlHpG6MARId1V4+ZbJ8ZTBHRC4ETOtJ2bhSVVMLz9QC3ffFKg9Pjj5bgrOpvIlar19wc2Jk802wIK9ugDnjLUBedOfdGFCVAN/GdYkNoiMfoIEycTNlAeJ9P5XOdFGYMOlPwKst27lIxc5XvchCckjgzUneLWGWlp6rV+xQ33hJ2DjE5AuakCRWYuZ8z2VnPQQzsm6vodAdvPuuP7zPa5a5uXAPnTXoSIP1Ba4Jf6MkCAnZRnSFvXdPwj+EkiNGFp6EGTHlzV5Bh2CWDwwJld6YbZTkJc4TjbIg9FHsAh8EPnTTkc3tuMhROuekLRL1e2hJYefXA/QiHDBvxtCHFMMuWZk8gNUs/w649ICWLEkRDHzmijxik8L/XnBlZ/v1Lac+aYY0kT9NkuKObUMReRMq3cNnuK6Kbcc6kxJHT7ccuFytQExE0A5xes7QwVVICygrIkZo4meXe/gCXSjDFjOJD7Yam9Kb9sDGbyyiK8=
  file: firmware/roomba_wall_v3.hex
  skip_cleanup: true
  on:
    repo: Petezah/roomba_wall_v3
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^master|develop$
