language: c
before_install:
- sudo apt-get update -qq
install:
- sudo apt-get install -qq gcc-avr binutils-avr avr-libc
script: make -C firmware
deploy:
  provider: releases
  api_key:
    secure: YZ0QovuJr/LsbNho1ph4b7yxvX8FS+NWc8L2p15J6h7M0YB5neKcJPiD7v72KCfWQziVuU2kdT/+q3QmyrOXc9nZr1YEOce/dQp5HqRN/XmbNyWxyfk4wItTx4b2bTQoxUkHalYtYzvXz1b5P6MzY/vlTDnx3khPEnTvWprwydjEbHSLCyUZpOTTK/7kYovC+/wdNxNNIPdcUfj/fBHbc9nF/pJAdFcMg2u+5iBKZmsWxcsM65rIFQlKbgevE+03TFJ/fbbcZ287XFQjheYp+azwqWoz3oZpHraDM7wua4sf07ghvtsv5EOh0mwFBLwaJEvlA06MahFeW7/6ahYlxcfyIOR2WOZd6MvKmtKUHW8X/0+xoMth4oBvTdLL7PrJTWEzx8MtgKarnHVUZ2bIdMF00JLH8ZUPK038lSFPfVUL6e7AXxvXLQ+JJAIwAKWKr04oxu9YNq+ZSUF77eHas7MgG7NHRsMMBRIm0n8Qtdg0P1jHtdPvpUSQCDbh5iPDFx9WHKCOmTXUwTFDZGTnlGiv8TlEQLGQZW/Gq3hhuCc/uwbNgkqXiOTb/oSwAfUm1nf5Vpdbz6OMOgaQ0K0NP24JYJ1aJFMW48xJxLqo2PykSQYi8MjU6obuwc9MgOYatsmRnE754YwQN3LeoiMtnoGoaDXkBFpJJ89i6dnaVNw=
  file: firmware/roomba_wall_v3.hex
  skip_cleanup: true
  on:
    tags: true